links = dict(
    donate="http://paypal.me/CRicoA",
    tutorials="http://paulwinex.com/portfolio/multi-script-editor",
    manual="https://github.com/charliewales/pw_MultiScriptEditor",
    blender_manual="https://docs.blender.org/manual/en/latest/",
    qt5_docs="https://doc.qt.io/qtforpython-5/contents.html",
    qt5_modules="https://doc.qt.io/qtforpython-5/modules.html",
    qt6_docs="https://doc.qt.io/qtforpython-6/contents.html",
    qt6_modules="https://doc.qt.io/qtforpython-6/modules.html",
    maya_cmds="https://help.autodesk.com/cloudhelp/2027/ENU/Maya-Tech-Docs/CommandsPython/index.html",
    houdini_hou="https://www.sidefx.com/docs/houdini/hom/hou/index.html",
    houdini_envs="https://www.sidefx.com/docs/houdini/ref/env.html",
    nuke_dev_guide="https://learn.foundry.com/nuke/developers/17.0/pythondevguide/#",
    site="http://www.paulwinex.com",
    python2="https://docs.python.org/2",
    python3="https://docs.python.org/3",
)
