# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\tools\pw_scriptEditor\widgets\themeEditor.ui'
#
# Created: Mon Mar 16 10:29:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!


from vendor.Qt.QtCore import QMetaObject, QSize, Qt
from vendor.Qt.QtWidgets import QApplication, QComboBox, QHBoxLayout, QLabel, QListWidget, QPushButton, QSizePolicy, QSpacerItem, QSpinBox, QSplitter, QVBoxLayout, QWidget, QFormLayout, QCheckBox, QGroupBox, QGridLayout

class Ui_themeEditor(object):
    def setupUi(self, themeEditor):
        themeEditor.setObjectName("themeEditor")
        themeEditor.resize(724, 461)
        self.verticalLayout_3 = QVBoxLayout(themeEditor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QSplitter(themeEditor)
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.colors_lwd = QListWidget(self.widget)
        self.colors_lwd.setObjectName("colors_lwd")
        
        self.horizontalLayout_font = QHBoxLayout()
        self.horizontalLayout_font.setObjectName("horizontalLayout_font")
        self.choose_font_btn = QPushButton(self.widget)
        self.choose_font_btn.setObjectName("choose_font_btn")
        self.horizontalLayout_font.addWidget(self.choose_font_btn)

        self.font_name_label = QLabel(self.widget)
        self.font_name_label.setObjectName("font_name_label")
        self.horizontalLayout_font.addWidget(self.font_name_label)
        spacerItemFont = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_font.addItem(spacerItemFont)
        self.verticalLayout_2.addLayout(self.horizontalLayout_font)

        self.verticalLayout_2.addWidget(self.colors_lwd)
        
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName("formLayout")
        
        self.fontSize_groupBox = QGroupBox(self.widget)
        self.fontSize_groupBox.setObjectName("fontSize_groupBox")
        self.fontSize_groupBox.setAlignment(Qt.AlignLeft)
        self.fontSize_layout = QGridLayout(self.fontSize_groupBox)
        self.fontSize_layout.setObjectName("fontSize_layout")

        self.label = QLabel(self.fontSize_groupBox)
        self.label.setObjectName("label")
        self.textSize_spb = QSpinBox(self.fontSize_groupBox)
        self.textSize_spb.setMinimum(6)
        self.textSize_spb.setMaximum(25)
        self.textSize_spb.setProperty("value", 10)
        self.textSize_spb.setObjectName("textSize_spb")
        self.fontSize_layout.addWidget(self.label, 0, 0)
        self.fontSize_layout.addWidget(self.textSize_spb, 0, 1)

        self.label_menuSize = QLabel(self.fontSize_groupBox)
        self.label_menuSize.setObjectName("label_menuSize")
        self.menuSize_spb = QSpinBox(self.fontSize_groupBox)
        self.menuSize_spb.setMinimum(6)
        self.menuSize_spb.setMaximum(25)
        self.menuSize_spb.setProperty("value", 10)
        self.menuSize_spb.setObjectName("menuSize_spb")
        self.fontSize_layout.addWidget(self.label_menuSize, 0, 2)
        self.fontSize_layout.addWidget(self.menuSize_spb, 0, 3)
        
        self.label_outlineSize = QLabel(self.fontSize_groupBox)
        self.label_outlineSize.setObjectName("label_outlineSize")
        self.outlineSize_spb = QSpinBox(self.fontSize_groupBox)
        self.outlineSize_spb.setMinimum(6)
        self.outlineSize_spb.setMaximum(30)
        self.outlineSize_spb.setProperty("value", 10)
        self.outlineSize_spb.setObjectName("outlineSize_spb")
        self.fontSize_layout.addWidget(self.label_outlineSize, 1, 0)
        self.fontSize_layout.addWidget(self.outlineSize_spb, 1, 1)
        
        self.label_outputSize = QLabel(self.fontSize_groupBox)
        self.label_outputSize.setObjectName("label_outputSize")
        self.outputSize_spb = QSpinBox(self.fontSize_groupBox)
        self.outputSize_spb.setMinimum(6)
        self.outputSize_spb.setMaximum(25)
        self.outputSize_spb.setProperty("value", 10)
        self.outputSize_spb.setObjectName("outputSize_spb")
        self.fontSize_layout.addWidget(self.label_outputSize, 1, 2)
        self.fontSize_layout.addWidget(self.outputSize_spb, 1, 3)
        
        self.label_statusBarSize = QLabel(self.fontSize_groupBox)
        self.label_statusBarSize.setObjectName("label_statusBarSize")
        self.statusBarSize_spb = QSpinBox(self.fontSize_groupBox)
        self.statusBarSize_spb.setMinimum(6)
        self.statusBarSize_spb.setMaximum(25)
        self.statusBarSize_spb.setProperty("value", 10)
        self.statusBarSize_spb.setObjectName("statusBarSize_spb")
        self.fontSize_layout.addWidget(self.label_statusBarSize, 2, 0)
        self.fontSize_layout.addWidget(self.statusBarSize_spb, 2, 1)
        
        self.label_tabSize = QLabel(self.fontSize_groupBox)
        self.label_tabSize.setObjectName("label_tabSize")
        self.tabSize_spb = QSpinBox(self.fontSize_groupBox)
        self.tabSize_spb.setMinimum(6)
        self.tabSize_spb.setMaximum(30)
        self.tabSize_spb.setProperty("value", 10)
        self.tabSize_spb.setObjectName("tabSize_spb")
        self.fontSize_layout.addWidget(self.label_tabSize, 2, 2)
        self.fontSize_layout.addWidget(self.tabSize_spb, 2, 3)
        self.fontSize_layout.setColumnStretch(4, 1)

        self.formLayout.addRow(self.fontSize_groupBox)
        
        self.label_radius = QLabel(self.widget)
        self.label_radius.setObjectName("label_radius")
        self.tabRadius_spb = QSpinBox(self.widget)
        self.tabRadius_spb.setMinimum(0)
        self.tabRadius_spb.setMaximum(50)
        self.tabRadius_spb.setProperty("value", 12)
        self.tabRadius_spb.setObjectName("tabRadius_spb")
        self.formLayout.addRow(self.label_radius, self.tabRadius_spb)
        self.useThemeFont_groupBox = QGroupBox(self.widget)
        self.useThemeFont_groupBox.setObjectName("useThemeFont_groupBox")
        self.useThemeFont_groupBox.setAlignment(Qt.AlignLeft)
        self.useThemeFont_layout = QGridLayout(self.useThemeFont_groupBox)
        self.useThemeFont_layout.setObjectName("useThemeFont_layout")

        self.completerFont_cb = QCheckBox(self.useThemeFont_groupBox)
        self.completerFont_cb.setObjectName("completerFont_cb")
        self.useThemeFont_layout.addWidget(self.completerFont_cb, 0, 0)
        
        self.menuFont_cb = QCheckBox(self.useThemeFont_groupBox)
        self.menuFont_cb.setObjectName("menuFont_cb")
        self.useThemeFont_layout.addWidget(self.menuFont_cb, 0, 1)
        
        self.outlineFont_cb = QCheckBox(self.useThemeFont_groupBox)
        self.outlineFont_cb.setObjectName("outlineFont_cb")
        self.useThemeFont_layout.addWidget(self.outlineFont_cb, 1, 0)
        
        self.statusBarFont_cb = QCheckBox(self.useThemeFont_groupBox)
        self.statusBarFont_cb.setObjectName("statusBarFont_cb")
        self.useThemeFont_layout.addWidget(self.statusBarFont_cb, 1, 1)
        
        self.tabFont_cb = QCheckBox(self.useThemeFont_groupBox)
        self.tabFont_cb.setObjectName("tabFont_cb")
        self.useThemeFont_layout.addWidget(self.tabFont_cb, 2, 0)
        self.useThemeFont_layout.setColumnStretch(2, 1)
        
        self.formLayout.addRow(self.useThemeFont_groupBox)
        
        self.horizontalLayout_formContainer = QHBoxLayout()
        self.horizontalLayout_formContainer.addLayout(self.formLayout)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_formContainer.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_formContainer)
        
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.themeList_cbb = QComboBox(self.layoutWidget)
        self.themeList_cbb.setObjectName("themeList_cbb")
        self.horizontalLayout.addWidget(self.themeList_cbb)
        self.save_btn = QPushButton(self.layoutWidget)
        self.save_btn.setMaximumSize(QSize(60, 16777215))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.del_btn = QPushButton(self.layoutWidget)
        self.del_btn.setMaximumSize(QSize(60, 16777215))
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout.addWidget(self.del_btn)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.preview_ly = QVBoxLayout()
        self.preview_ly.setObjectName("preview_ly")
        self.verticalLayout.addLayout(self.preview_ly)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.apply_btn = QPushButton(themeEditor)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout_2.addWidget(self.apply_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 1)

        self.retranslateUi(themeEditor)
        QMetaObject.connectSlotsByName(themeEditor)

    def retranslateUi(self, themeEditor):
        themeEditor.setWindowTitle(QApplication.translate("themeEditor", "Code Theme Editor", None))
        self.label_radius.setText(QApplication.translate("themeEditor", "Tab border radius", None))
        self.tabRadius_spb.setToolTip(QApplication.translate("themeEditor", "Set the border radius (roundness) for the tabs", None))
        
        self.fontSize_groupBox.setTitle(QApplication.translate("themeEditor", "Font size", None))
        self.label.setText(QApplication.translate("themeEditor", "Completer", None))
        self.textSize_spb.setToolTip(QApplication.translate("themeEditor", "Set the font size for the completer list", None))
        self.label_menuSize.setText(QApplication.translate("themeEditor", "Menu", None))
        self.menuSize_spb.setToolTip(QApplication.translate("themeEditor", "Set the font size for the menus", None))
        self.label_outlineSize.setText(QApplication.translate("themeEditor", "Outline", None))
        self.outlineSize_spb.setToolTip(QApplication.translate("themeEditor", "Set the font size for the outline view", None))
        self.label_outputSize.setText(QApplication.translate("themeEditor", "Output", None))
        self.outputSize_spb.setToolTip(QApplication.translate("themeEditor", "Set the font size for the output console", None))
        self.label_statusBarSize.setText(QApplication.translate("themeEditor", "Status bar", None))
        self.statusBarSize_spb.setToolTip(QApplication.translate("themeEditor", "Set the font size for the status bar", None))
        self.label_tabSize.setText(QApplication.translate("themeEditor", "Tab label", None))
        self.tabSize_spb.setToolTip(QApplication.translate("themeEditor", "Set the font size for the tab labels", None))
        
        self.useThemeFont_groupBox.setTitle(QApplication.translate("themeEditor", "Use theme font", None))
        self.completerFont_cb.setText(QApplication.translate("themeEditor", "Completer", None))
        self.completerFont_cb.setToolTip(QApplication.translate("themeEditor", "Use the custom theme font for the completer list", None))
        self.menuFont_cb.setText(QApplication.translate("themeEditor", "Menus", None))
        self.menuFont_cb.setToolTip(QApplication.translate("themeEditor", "Use the custom theme font for the menus", None))
        self.outlineFont_cb.setText(QApplication.translate("themeEditor", "Outline", None))
        self.outlineFont_cb.setToolTip(QApplication.translate("themeEditor", "Use the custom theme font for the outline view", None))
        self.statusBarFont_cb.setText(QApplication.translate("themeEditor", "Status bar", None))
        self.statusBarFont_cb.setToolTip(QApplication.translate("themeEditor", "Use the custom theme font for the status bar", None))
        self.tabFont_cb.setText(QApplication.translate("themeEditor", "Tab label", None))
        self.tabFont_cb.setToolTip(QApplication.translate("themeEditor", "Use the custom theme font for the tab labels", None))
        
        self.save_btn.setText(QApplication.translate("themeEditor", "Save", None))
        self.save_btn.setToolTip(QApplication.translate("themeEditor", "Save current settings to a new theme", None))
        self.del_btn.setText(QApplication.translate("themeEditor", "Del", None))
        self.del_btn.setToolTip(QApplication.translate("themeEditor", "Delete the selected theme", None))
        self.apply_btn.setText(QApplication.translate("themeEditor", "Save", None))
        self.apply_btn.setToolTip(QApplication.translate("themeEditor", "Apply the selected theme to the editor", None))
        self.choose_font_btn.setText(QApplication.translate("themeEditor", "Choose Font", None))
        self.choose_font_btn.setToolTip(QApplication.translate("themeEditor", "Select a custom font family", None))
        self.font_name_label.setText(QApplication.translate("themeEditor", "Default", None))
        self.themeList_cbb.setToolTip(QApplication.translate("themeEditor", "Select a theme to edit or apply", None))

